package is.fon.rs.domain;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
// Generated Aug 2, 2014 1:48:10 AM by Hibernate Tools 3.2.1.GA

/**
 * AcademicExpertise generated by hbm2java
 */
@Entity
@Table(name="academic_expertise")
public class AcademicExpertise implements java.io.Serializable {
    
    @Id
    @GeneratedValue
    @Column(name="academic_expertise_id")
    private Integer academicExpertiseId;
    @Column(name="name")
    private String name;
    @Column(name="description")
    private String description;

    public AcademicExpertise() {
    }

    public AcademicExpertise(String name, String description) {
        this.name = name;
        this.description = description;
    }

    public Integer getAcademicExpertiseId() {
        return this.academicExpertiseId;
    }

    public void setAcademicExpertiseId(Integer academicExpertiseId) {
        this.academicExpertiseId = academicExpertiseId;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        return name;
    }
}
