package is.fon.rs.domain;
// Generated Aug 2, 2014 1:48:10 AM by Hibernate Tools 3.2.1.GA

import java.util.ArrayList;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.Transient;

/**
 * Documents generated by hbm2java
 */
@Entity
@Table(name="documents")
public class Documents implements java.io.Serializable {

    @Id
    @GeneratedValue
    @Column(name="document_id")
    private Integer documentId;
    @Column(name="document_title")
    private String documentTitle;
    @Column(name="file_name")
    private String fileName;
    @Column(name="file_size")
    private String fileSize;
    @Column(name="author_firstname")
    private String authorFirstname;
    @Column(name="author_lastname")
    private String authorLastname;
    @Column(name="copyright_year")
    private int copyrightYear;
    @Column(name="uploaded")
    @Temporal(javax.persistence.TemporalType.DATE)
    private Date uploaded;
    @Column(name="academic_expertise_id")
    private int academicExpertiseId;
    @Column(name="keywords")
    private String keywords;

    @Transient
    private ArrayList<String> keywordsList; 
    @Transient
    private ArrayList<String> commonKeywordsList;     

    @Transient
    private AcademicExpertise academicExpertise;

    public AcademicExpertise getAcademicExpertise() {
        return academicExpertise;
    }

    public void setAcademicExpertise(AcademicExpertise academicExpertise) {
        this.academicExpertise = academicExpertise;
    }

    public String getKeywords() {
        return keywords;
    }

    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

    public ArrayList<String> getKeywordsList() {
        return keywordsList;
    }

    public void setKeywordsList(ArrayList<String> keywordsList) {
        this.keywordsList = keywordsList;
    }



    public Documents() {
    }

    public Documents(String documentTitle, String fileName, String fileSize, String authorFirstname, String authorLastname, int copyrightYear, Date uploaded, int academicExpertiseId, String keywords) {
        this.documentTitle = documentTitle;
        this.fileName = fileName;
        this.fileSize = fileSize;
        this.authorFirstname = authorFirstname;
        this.authorLastname = authorLastname;
        this.copyrightYear = copyrightYear;
        this.uploaded = uploaded;
        this.academicExpertiseId = academicExpertiseId;
        this.keywords = keywords;
    }

    public Integer getDocumentId() {
        return this.documentId;
    }

    public void setDocumentId(Integer documentId) {
        this.documentId = documentId;
    }

    public String getDocumentTitle() {
        return this.documentTitle;
    }

    public void setDocumentTitle(String documentTitle) {
        this.documentTitle = documentTitle;
    }

    public String getFileName() {
        return this.fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getFileSize() {
        return this.fileSize;
    }

    public void setFileSize(String fileSize) {
        this.fileSize = fileSize;
    }

    public String getAuthorFirstname() {
        return this.authorFirstname;
    }

    public void setAuthorFirstname(String authorFirstname) {
        this.authorFirstname = authorFirstname;
    }

    public String getAuthorLastname() {
        return this.authorLastname;
    }

    public void setAuthorLastname(String authorLastname) {
        this.authorLastname = authorLastname;
    }

    public int getCopyrightYear() {
        return this.copyrightYear;
    }

    public void setCopyrightYear(int copyrightYear) {
        this.copyrightYear = copyrightYear;
    }

    public Date getUploaded() {
        return this.uploaded;
    }

    public void setUploaded(Date uploaded) {
        this.uploaded = uploaded;
    }

    public int getAcademicExpertiseId() {
        return this.academicExpertiseId;
    }

    public void setAcademicExpertiseId(int academicExpertiseId) {
        this.academicExpertiseId = academicExpertiseId;
    }
    
    public ArrayList<String> getCommonKeywordsList() {
        return commonKeywordsList;
    }

    public void setCommonKeywordsList(ArrayList<String> commonKeywordsList) {
        this.commonKeywordsList = commonKeywordsList;
    }    
}
